version: '3'

services:

  front:
    container_name: front
    build: ./6ch-front/
    ports:
      - 3000:3000
    volumes:
      - ./6ch-front/:/usr/app
      - /usr/app/node_modules
    depends_on:
      - backend
    entrypoint: /usr/app/start.sh

  backend:
    container_name: backend
    build: ./6ch-backend
    ports:
      - 9000:9000
    volumes:
      - ./6ch-backend:/usr/app
      - ~/.sbt:/root/.sbt
      - ~/.ivy2:/root/.ivy2
      - ~/.m2:/root/.m2
    depends_on:
      - database
    command: sh -c "sleep 20 && sbt run"

  database:
    container_name: database
    build: ./database
    ports:
      - 4306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: "6ch"
