# --- !Ups

CREATE TABLE IF NOT EXISTS thread (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
  title VARCHAR(100) NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  active BOOLEAN NOT NULL DEFAULT true,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS post (
id INT UNSIGNED NOT NULL AUTO_INCREMENT UNIQUE,
user_name VARCHAR(250) NOT NULL,
content VARCHAR(250) NOT NULL,
created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
thread_id INT UNSIGNED NOT NULL,
PRIMARY KEY (id),
CONSTRAINT post_ibfk_1 FOREIGN KEY (thread_id) REFERENCES thread(id) ON DELETE CASCADE
);

# --- !Downs
DROP TABLE post;
DROP TABLE thread;
